name: switcher
description: A new Flutter module project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.5.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^4.2.2
  
flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: de.develappers.switcher
    iosBundleIdentifier: de.develappers.switcher
